# Generated by Django 5.2.1 on 2025-06-07 05:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('kode_barang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('satuan', models.CharField(max_length=20)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.IntegerField(primary_key=True, serialize=False)),
                ('customer', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah', models.PositiveIntegerField()),
                ('total_harga', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('waktu_transaksi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='produk.produk')),
            ],
        ),
    ]
