# Generated by Django 5.2.1 on 2025-05-30 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produk',
            fields=[
                ('kode_barang', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('satuan', models.CharField(max_length=20)),
                ('harga_satuan', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id_transaksi', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah', models.PositiveIntegerField()),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produk.produk')),
            ],
        ),
    ]
