# Generated by Django 5.2.1 on 2025-06-05 05:00

import django.db.models.deletion
import produk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0001_initial'),
        ('user', '0004_user_delete_pengguna'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='customer',
            field=models.ForeignKey(default=produk.models.get_default_customer_pk, on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='user.user'),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='total_harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='transaksi',
            name='waktu_transaksi',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='produk',
            field=models.ForeignKey(default=produk.models.get_default_produk_pk, on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='produk.produk'),
        ),
    ]
