# Generated by Django 5.2.1 on 2025-06-05 05:06

import produk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_transaksi_customer_transaksi_total_harga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='customer',
            field=models.CharField(default=produk.models.get_default_customer_pk, max_length=100),
        ),
    ]
