# Generated by Django 5.2.1 on 2025-06-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0002_alter_transaksi_jumlah'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='harga_modal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
