# Generated by Django 5.2.1 on 2025-06-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_produk_harga_modal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='harga_modal',
        ),
    ]
