# Generated by Django 5.2.1 on 2025-06-06 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0003_alter_transaksi_customer'),
        ('user', '0005_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='produk',
            name='stok',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='user.user'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='produk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaksi', to='produk.produk'),
        ),
    ]
