# Generated by Django 5.2.1 on 2025-06-06 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0004_produk_stok_alter_transaksi_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='id_transaksi',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='waktu_transaksi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
