# Generated by Django 5.2.1 on 2025-06-06 16:32

import django.db.models.deletion
import produk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0005_transaksi_created_at_alter_transaksi_customer_and_more'),
        ('user', '0005_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='customer',
            field=models.ForeignKey(default=produk.models.get_default_customer_pk, on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_list', to='user.user'),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='total_harga',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
