# Generated by Django 5.2.1 on 2025-06-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0006_alter_transaksi_customer_alter_transaksi_total_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='total_harga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
