# Generated by Django 5.2.1 on 2025-06-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produk', '0007_alter_transaksi_customer_alter_transaksi_total_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='harga_satuan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaksi',
            name='jumlah',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
