# Generated by Django 5.2.1 on 2025-06-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id_pengguna', models.AutoField(primary_key=True, serialize=False)),
                ('nama_pengguna', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('kata_sandi', models.CharField(max_length=128)),
                ('nama_lengkap', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
