# Generated by Django 5.2.1 on 2025-06-01 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_pengguna_date_joined_pengguna_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='id_pengguna',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
